In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# in this notebook we're going to see:
<ul>
    <li>how to solve a liner equation system using numpy (Cramer's rule)</li>
    <li>latex functions on jupyter</li>
    
</ul>    

<p> <b>fonts: </b> </p>

<p>https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd </p>
<p>https://www.youtube.com/watch?v=oGYDPxcNMmw&list=PLxI8Can9yAHdUtWDKtTA9AmuICNyX9EIr&index=6&t=0s</p>


### problem to solve:

\begin{equation}
  \begin{pmatrix}
    5 & 4 & 3 & 2\\
    4 & 2 & 6 & 3\\
    3 & 1 & 7 & 5\\
    2 & 3 & 5 & 1
   \end{pmatrix}
  \cdot
  %
  \begin{pmatrix}
    x_1 \\
    x_2 \\
    x_3 \\
    x_4 \\
  \end{pmatrix}
  =
  %
   \begin{pmatrix}
    1496 \\
    1175 \\
    958 \\
    861 \\
  \end{pmatrix} 
\end{equation}

### 1) creating the matrix

In [19]:
matrix = np.matrix([[5,4,3,2],
                    [4,2,6,3],
                    [3,1,7,5],
                    [2,3,5,1]])
det_matrix = np.linalg.det(matrix)
print(det_matrix)
matrix

92.99999999999994


matrix([[5, 4, 3, 2],
        [4, 2, 6, 3],
        [3, 1, 7, 5],
        [2, 3, 5, 1]])

In [20]:
response = np.matrix([1496,1175,958,861]).T
response

matrix([[1496],
        [1175],
        [ 958],
        [ 861]])

In [22]:
a = matrix.copy()
a[:,0] = response
det_a = np.linalg.det(a)
print(det_a)
a

16460.999999999985


matrix([[1496,    4,    3,    2],
        [1175,    2,    6,    3],
        [ 958,    1,    7,    5],
        [ 861,    3,    5,    1]])

In [24]:
b = matrix.copy()
b[:,1]= response
det_b = np.linalg.det(b)
print(det_b)
b

11252.999999999987


matrix([[   5, 1496,    3,    2],
        [   4, 1175,    6,    3],
        [   3,  958,    7,    5],
        [   2,  861,    5,    1]])

In [26]:
c = matrix.copy()
c[:,2]= response
det_c = np.linalg.det(c)
print(det_c)
c

2139.000000000001


matrix([[   5,    4, 1496,    2],
        [   4,    2, 1175,    3],
        [   3,    1,  958,    5],
        [   2,    3,  861,    1]])

In [28]:
d = matrix.copy()
d[:,3]= response
det_d = np.linalg.det(d)
print(det_d)
d

2696.999999999988


matrix([[   5,    4,    3, 1496],
        [   4,    2,    6, 1175],
        [   3,    1,    7,  958],
        [   2,    3,    5,  861]])

### 2) calculate the coefs

In [32]:
coef_a = det_a/det_matrix
coef_b = det_b/det_matrix
coef_c = det_c/det_matrix
coef_d = det_d/det_matrix
print('coef a :' , coef_a)
print('coef b :' , coef_b)
print('coef c :' , coef_c)
print('coef d :' , coef_d)

coef a : 176.99999999999994
coef b : 120.99999999999994
coef c : 23.000000000000025
coef d : 28.99999999999989
